---
# This role contains common plays that will run on all nodes.

- name: apt update
  apt: update_cache=yes

- name: Apt-Transport-Https
  apt: name=apt-transport-https state=installed

- name: Ca-Certificates
  apt: name=ca-certificates state=installed

- name: Create the repository for docker
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list

- name: Update the signing key for docker
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: apt update
  apt: update_cache=yes

- name: Install docker
  apt: name=docker-engine state=installed

- name: Install ntp
  apt: name=ntp state=installed
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
     - restart ntp
  tags: ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: State docker service
  service: name=docker state=started enabled=yes
  tags: docker
